#+title: xlib
#+description: X11 Library
#+author: Richard Westhaver
#+email:richard.westhaver@gmail.com
This is a fork of CLX built for the Cursed Linux environment.

#+BEGIN: project-info :files nil :tasks nil :status nil :churn t :html nil
#+CALL: project-details(vc='nil) :dir ~/comp/shed/xlib/

#+RESULTS:
|-------------+---------------------------------------------|
| name        | xlib                                        |
| version     | 1.0.0                                       |
| description | A fork of CLX maintained by Sharplispers    |
| id          | 3818250095842153598                         |
| root        | ~/comp/shed/xlib/                           |
| tags        | x                                           |
| updated     | Sat Jan 24 20:58:31 2026 -0500              |
| langs       | lisp org                                    |
| lines       | 30157 :code 24608 :comment 3092 :blank 2457 |
|-------------+---------------------------------------------|

#+CALL: hg-churn() :dir ~/comp/shed/xlib/

#+RESULTS:
: 2025-11  37657 *************************************************************
: 2025-12      9 
: 2026-01  10490 ****************

#+END:

#+begin_quote
Portions Copyright (C) 1987 Texas Instruments Incorporated.
Portions Copyright (C) 1988-1989 Franz Inc, Berkeley, Ca.
Portions Copyright (C) 2000-2024 Independent FOSS developers

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
“Software”), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+end_quote
